export const VRF_LIST: string[] = [
  'ABC_BANK_VRF', 'ACE_B2B', 'ADDIWEN_Soukra_B2B', 'ADSL_Boutique_VRF',
  'ADVYTEAM_B2B', 'AFA-VRF', 'AIL.Tunisie_VRF', 'ALUMENAGE_VRF',
  'AMBA_Resdi_Marsa_VRF', 'AMB_FRANCE_Lib_VOIP', 'AMEUR_Plastic_VRF',
  'AOUDA_MSSP', 'APO_B2B', 'ARAB_SOFT_VRF', 'ARAMYS_VRF', 'ARCHIDOC_VRF',
  'ARMATECH_VRF', 'ASTUEL_TUNISIE_MSSP', 'ASW3_VRF', 'ATB_Banque_VRF',
  'ATELIER_ISA', 'ATOL_B2B', 'AURA-BusinessVoice', 'AURA-Trunk-clients',
  'AYEM_ZMEN_VRF', 'Al-Baraka.VRF', 'Almaviva_VRF', 'Alpha_Hunday',
  'Altiad_Kal_Info_B2B', 'Ambassade_Lybie_FR_B2B', 'Amen_Bank_VRF',
  'Aramex_B2B', 'Aramex_VRF', 'Ashtart_VRF', 'Astree_LAC_B2B',
  'Astree_MPLS-VRF', 'Attijari_finance_B2B', 'Attijari_leasing_B2B',
  'Attijeri-Intra-VRF', 'Autoroute_VRF', 'Axiomata_VOIP', 'BACOVET-VRF',
  'BANSARD_MSSP', 'BCT-MPLS_VRF', 'BCT-Partenaire_VRF', 'BEST_BUY_TUNISIE',
  'BEST_TIME_TRAVEL', 'BH_Communication_B2B', 'BIAT_Inter_Agence_VRF',
  'BNA_Avaya_B2B', 'BNA_Siege_to_BNA_capitaux_VRF', 'BOUMIZA_CONCEPT_VRF',
  'BOUZIDBEHHI_VRF', 'BTE_Banque_VRF', 'BTK_VRF', 'BT_VRF', 'Biatlac1_B2B',
  'Business_Decision_B2B', 'Business_WIFI_Control', 'CCIT_VRF',
  'CCTV_Wimax_VRF', 'CIMENTS_GABES_B2B', 'CMR-Meninx_VRF', 'CNSS_vpn',
  'COMPLEXE-TLILI_VRF', 'COPTUPAP_VRF', 'CTFCI_B2B', 'CTF_VRF',
  'CYTOPHARMA_VRF', 'Client_UIB_VRF', 'DASRI_VRF', 'DOREMAIL_Depot_B2B',
  'DOREMAIL_Usine_B2B', 'Denim_B2B', 'Draxmailer_MPLS_VRF', 'EDUFRANCE-VRF',
  'ENNADHAFA_JUDY_VRF', 'ESPACE_WAHIBA_VRF', 'ETAP-VRF', 'ETAP_VRF_test',
  'ETS-DOUIK-VRF', 'Electrica_B2B', 'Extrum_Lac_B2B', 'FLORA_VRF',
  'Filtrage_B2B', 'Filtrage_VDOM_Niveau_3', 'First_Delivery_VRF',
  'Fortimanager_B2B', 'Fournisseurs-VOIP-International', 'FreeDom_B2B',
  'FrontDoor', 'GIF_VRF', 'GPON_BTQ_VRF', 'GROUPE_ALFA_vpn',
  'Ghaith_Avaya_B2B', 'Globalnet_B2B_VRF', 'Groupe_alaya_VRF',
  'HLOUWA_INDISTRIE', 'HORTIMAG_MSSP', 'HOTEL_KARAWEN_B2B', 'Henekl_VRF',
  'Henkel_VOIP_B2B', 'Hotel_Lodge_B2B', 'Hotspot_Wifi_Controller', 'IAT_B2B',
  'ICMPD_B2B', 'IMSET_VRF', 'INTERBRANDS_VRF', 'ITALCAR_Lac_B2B',
  'ITALCAR_MSSP', 'Internet', 'Internet_Backup_TDD', 'Internet_Didon',
  'Intra_orange_VRF', 'JARZIS_DECOR_MSSP', 'JunosSpace', 'LEGACY_VRF',
  'LGF_B2B', 'LNS_VRF', 'LONGCHAMP_B2B', 'Laghmani_Archeveche_B2B',
  'Leoni_Nord_B2B', 'Leoni_Sud_B2B', 'Link_Biat_Partenaire_VRF',
  'Loghmani_Kram_B2B', 'MAGHREB-STONE_VRF', 'MAG_ING_B2B', 'MEDDIS_MPLS_VOIP',
  'MEDDIS_VRF', 'MERCK_B2B', 'MEZZO_VOIP_B2B', 'MGT_B2B_FW',
  'MGT_B2B_FW-PreProd', 'MGT_SBC-PreProd', 'MILLESIMA_B2B', 'MNG_RDL3000',
  'MNG_VRF', 'MONOPRIX_DVR-VRF', 'MPC-PROKIM', 'MSSPv2', 'Maquart_FullIP_VOIP',
  'Meddis_Djerba_B2B', 'Metal_Shahel_B2B', 'Microtechnic_B2B',
  'MonitoringB2B_vpn', 'Monoprix_VRF', 'Moteur_VRF', 'NAIB_BANK-VRF',
  'NovoNordisk_B2B', 'OMV_VRF', 'OVH_VOIP_B2B', 'Omega_VRF', 'Orange_VRF',
  'PARENIN_VRF', 'POLYCLINIQUE_CAPBON_B2B', 'PROMODAR_VRF',
  'PaP_Loghmani_Dhrif_Kram_VRF', 'Parfois_MALL_B2B', 'Perenco_VRF',
  'Petrofac_Karekna_Ain_VRF', 'Petrofac_VRF', 'Phoenix_B2B', 'Poste_VRF',
  'Poulina_VRF', 'Predicitx_B2B', 'Promodar_Marsa_B2B', 'RoamSmart-VRF',
  'SEEM_SIEGE_B2B', 'SHDT_B2B', 'SIAME.VRF', 'SIMPA_VRF',
  'SLM_Boumhal_VOIP_B2B', 'SLM_EzzahraVoip_B2B', 'SLM_VRF', 'SMG_VRF',
  'SNBG_VRF', 'SOS_VILLAGE_VRF', 'STB.SMT_VRF', 'STB_Banque_VRF', 'STEG_VRF',
  'STEP-SA_VRF', 'STE_EXPLORATION_MSSP', 'STE_PRO_ASSUR_MSSP',
  'STIMEC-UBCI_VRF', 'STS_SIDI-HAMID_B2B', 'SUEZ_VRF', 'Sibtel_VRF',
  'Sitex_VRF', 'Sofrecom_VRF', 'TDS_AVAYA_B2B', 'TEST_QOS_VOIP_B2B',
  'TE_Connectivity_B2B', 'TOTAL_VoIP_B2B', 'TPS.Delta_VRF',
  'TPS.TANK-Batterie_VRF', 'TTR_VRF', 'TURKISH_AIRLINES_VRF', 'TX-MP_B2B',
  'Teleperformance_Data_VRF', 'Teleperformance_MGT_VRF', 'Teleperformance_Voix_VRF',
  'Teletravail', 'Test-IMS', 'Test-RDL-3000_VPLS', 'Test_AVAYA_TDD',
  'Timar_MSSP', 'Timsoft_LAC1_B2B', 'Tresselec_B2B', 'Tunisair_VRF',
  'UBCI_VRF', 'UIB_Hosting_VRF', 'UPSAT_B2B', 'VALEO_Enfidha_B2B',
  'Voice_vpn', 'Wifi_Control_VRF', 'Wifi_SMS_Notification_VRF',
  'Zitouna_Bank_VRF', 'carrefour_VRF', 'draexlmaier_JEM_VOIP_B2B',
  'guest_VRF', 'ipsla_oam_vpn', 'seem_VRF', 'tech_env_MP', 'test_vidom_niveau_2'
];
